openapi: 3.0.3
info:
  title: Greeter API
  version: 1.0.0

servers:
  - url: "http://localhost:8080"
    description: "Debug"

tags:
  - name: "greeter"
    description: "Greeter"

paths:
  /hello:
    get:
      tags:
        - greeter
      summary: Returns a greeting message.
      parameters:
        - name: name
          in: query
          description: Name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
